### ISSUE TITLE
GM tracklist is empty

### ISSUE THREAD

**Issue by megamegax** [ewnd9/badtaste#19]
I go to GM Play album -» search dialog appear -» i write in something (should exist)
-» and no logs, just waits.

**Comment by ewnd9** [comment]
I've updated my debug gist, please try it https://gist.github.com/ewnd9/132889c486ffffb6f3c5.

**Comment by megamegax** [comment]
getFavotites 0
search [Error: error getting search results: Error: 404 error from server]
getAllTracks 915

**Comment by ewnd9** [comment]
Looking like search is not available without "All access" :crying_cat_face:

**Comment by megamegax** [comment]
:'( getAllTracks is looks like working what about search locally if normal search said 404?

**Comment by ewnd9** [comment]
Yep, local search is totally needed to be implemented for all types of playlists, I'll create a separate issue.

**Comment by ewnd9** [comment]
Now you can activate search by pressing "f" button in badtaste in `v0.6.0` :balloon:
