### ISSUE TITLE
stream not starting from GM All tracks

### ISSUE THREAD

**Issue by megamegax** [ewnd9/badtaste#25]
Tracks appear in the list, I select one aaand nothing. Playing works if i am using vk or fs.

**Comment by ewnd9** [comment]
Okay, gist is in a game again https://gist.github.com/ewnd9/132889c486ffffb6f3c5. I'm particularly interested in `storeId` and `id`. You can also check if stream urls work for you by simply pasting them to browser

**Comment by megamegax** [comment]
node index.js
[ 'androidId', 'masterToken' ]
getFavotites 0
search [Error: error getting search results: Error: 404 error from server]
getAllTracks 894
storeId Thvmnov3k2zrmfsdhcjzgt5ttmy
id 19682bf0-df7d-377a-a673-cf58aa85a564
getStreamUrl storeId [Error: Unable to get stream urlError: 404 error from server]
getStreamUrl id https://sj.googleusercontent.com/stream?id=f31c77267ae2aad4&itag=25&source=skyjam_user_upload&begin=0&o=11159146887219065279&ip=0.0.0.0&ipbits=0&expire=1447934115&sparams=id,itag,source,o,ip,ipbits,expire&signature=8E4EF97E53080AC1972418E91E6C353F4738EDA2.2A61B56C939498EBF19BF8E09101C1EFB53376C2&key=sj3

streamurl id is working.

**Comment by ewnd9** [comment]
Did you look in `~/.badtaste-npm-info.log`? It contains either url of stream or exception stack trace

**Comment by megamegax** [comment]
{"cause":{},"isOperational":true}
    at
/usr/local/lib/node_modules/badtaste/node_modules/playmusic/play.js:299:22
    at IncomingMessage.<anonymous>
(/usr/local/lib/node_modules/badtaste/node_modules/playmusic/play.js:86:48)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickDomainCallback (node.js:463:13)
{"cause":{},"isOperational":true}
    at
/usr/local/lib/node_modules/badtaste/node_modules/playmusic/play.js:299:22
    at IncomingMessage.<anonymous>
(/usr/local/lib/node_modules/badtaste/node_modules/playmusic/play.js:86:48)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickDomainCallback (node.js:463:13)
Error: connect ETIMEDOUT
    at errnoException (net.js:904:11)
    at Object.afterConnect [as oncomplete](net.js:895:19)

ewnd9 notifications@github.com ezt írta (időpont: 2015. nov. 19., Cs,
13:00):

**Comment by ewnd9** [comment]
Try `v0.6.1`

**Comment by megamegax** [comment]
it works :) fixed ^^

ewnd9 notifications@github.com ezt írta (időpont: 2015. nov. 19., Cs,
13:15):

**Comment by ewnd9** [comment]
:tada: thanks for helping
