### ISSUE TITLE
Light terminal theme

### ISSUE THREAD

**Issue by slonoed** [ewnd9/badtaste#5]
<img width="1440" alt="2015-09-28_1135" src="https://cloud.githubusercontent.com/assets/463239/10130933/23eb54de-65d5-11e5-9507-cdec76c4c8e2.png">

Не очень хорошо выглядит в светлой схеме. Может лучше не хардкодить цвета, а использовать стандартный basic цвета, который меняются в настройках консоли (iterm2 в моем случае)?
Я возможно не очень хорошо объяснил, если нужно попробую подробнее мысль изложить.

**Comment by ewnd9** [comment]
Спасибо за фидбек, откатил к стандартным цветам в `v.0.1.1`. В моем светлой теме отображаться стало вполне ок. 

Отпишись, пожалуйста, в ewnd9/badtaste#2 ещё по запуску на mac os.

было
![2015-09-28-151745_722x434_scrot](https://cloud.githubusercontent.com/assets/1713789/10135209/87419452-65f4-11e5-8916-c6713967bbc2.png)

стало
![2015-09-28-151817_722x434_scrot](https://cloud.githubusercontent.com/assets/1713789/10135210/87447c4e-65f4-11e5-8927-c3e8100cc0bb.png)

**Comment by slonoed** [comment]
Спасибо! Теперь все отлично.
